Homework 2
Hmlny/YuriyKhmelinsky_LevelUp pull request #1
Opened 2022-06-20 15:08 UTC by Hmlny

https://github.com/lemmy90/NadezhdaLemekhova_LevelUp/pull/2

2022-06-20 15:42 UTC, khda91 requested changes
исправить проблему запуска тестов по сьютьам

2022-06-20 15:42 UTC, khda91 commented on pom.xml
> +                <!--         <configuration>
А для чего конфигурация закомментирована? Как я вижу работает только 1 suite  и выбрать другой нет возможности

2022-06-23 15:31 UTC, Hmlny commented on pom.xml
> +                <!--         <configuration>
разобрался, добавил запуск тестов через профиль

2022-06-23 15:33 UTC, Hmlny commented on pom.xml
> +                <!--         <configuration>
нужно создавать новый пулреквест?

2022-06-24 18:09 UTC, khda91 requested changes
исправить запуск сьюта который падает

2022-06-24 18:09 UTC, khda91 commented on pom.xml
> +            <id>sub-div-tests</id>
![image](https://user-images.githubusercontent.com/7585107/175618139-89df4bc7-bea5-4b90-a120-4da823b41284.png)

2022-07-17 20:15 UTC, khda91 approved these changes
Домашняя работа принята

2022-07-17 20:15 UTC, merged